

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_300 = Integer(300); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_10000 = Integer(10000); _sage_const_20 = Integer(20)
reset()

#the following parameters must be set-up before launching this script:

#degree of polynomial
deg=_sage_const_4 
#bounds on height of initial and shifted polynomials
h_max = _sage_const_5 
c_max = _sage_const_300 
#bounds on the size of the shift
s_max=_sage_const_10 
#number of zeros allowed
z_max=_sage_const_1 
#number of tries
num_tries=_sage_const_10000 
#number of tests
num_probs = _sage_const_20 

load('genTaylor.sage')
load('genfiles.sage')

reset()

