

# This file was *autogenerated* from the file genfiles.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)#---------------------------------------------------------------------
#the following parameters must be set-up before launching this script:
try:
    mat_lst
except NameError:
    mat_lst = []
try:
    vec_lst
except NameError:
    vec_lst = []
try:
    answ_lst
except NameError:
    answ_lst = []
#---------------------------------------------------------------------
try:
    start
except NameError:
    start = _sage_const_0 
#---------------------------------------------------------------------
#Read template text
file_ext = '.xml'
tmpl_file_name = 'template' + file_ext

tmpl = open(tmpl_file_name, 'r')
otxt = tmpl.read()
tmpl.close()

#---------------------------------------------------------------------
#Produce quiz files
    
n = min(len(mat_lst), len(vec_lst), len(answ_lst))
for i in range(n):

    mat = mat_lst[i]
    vec = vec_lst[i]
    ans = answ_lst[i]

    ndim = mat.ncols()

    #strip vector answer string from spaces and parantheses
    answ_txt = str(ans)
    rems = {' ': '', '(': '', ')': ''}
    for s in rems.keys():
        answ_txt = answ_txt.replace(s, rems[s])

    #template text substitutions
    subs1 = {'$v'+str(i)+'$': str(mat.columns[i-_sage_const_1 ]) for i in range(_sage_const_1 , ndim+_sage_const_1 )}
    subs2 = {'$id$': str(i+start), '$matrix$': latex(mat), '$inverse$': latex(mat.inverse()),'$v$': str(vec), '$answ$': answ_txt}
    subs = {**subs1, **subs2}

    ntxt = otxt 
    for s in subs.keys():
        ntxt = ntxt.replace(s, subs[s])
    
    file_name_pfx = 'Koordinatės ' + str(vec) + 'dim' + str(ndim) + ' bazėje'
    outp = open(file_name_pfx + ' (' + str(idx) + ') ' + file_ext, 'w')
    outp.write(ntxt)
    outp.close()

