

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20)
reset()
#----------------------------------------
#set-up script parameters
#largest matrix element (default value)
h_max = _sage_const_8 
#bound for no. of zeros in row or column
z_max = _sage_const_2 

#number of rows and columns
ndim = _sage_const_3 
#rank
rg = _sage_const_3 

#starting id number
start = _sage_const_0 


#number of matrices
mat_num = _sage_const_20 

#----------------------------------------
load('genmat.sage')

load('genfiles.sage')

#----------------------------------------
#cleanup
reset()

