

# This file was *autogenerated* from the file gensym.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_100 = Integer(100); _sage_const_400 = Integer(400); _sage_const_50 = Integer(50); _sage_const_1000 = Integer(1000); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
import random as rnd

load('../matrix_utils.sage')

#-----------------------------------------------------------------------------
#the following parameters must be set-up before launching this script:
#matrix dimensions
try:
    ndim
except NameError:
    ndim = _sage_const_3 

#rank of th restricted subspace
try:
    rg
except NameError:
    rg = _sage_const_1 

   
#largest allowed matrix elements

try:
    h_t_max
except NameError:
    h_t_max = _sage_const_100 

try:
    h_ort_max
except NameError:
    h_ort_max = _sage_const_400 


try:
    h_max
except NameError:
    h_max = _sage_const_50 

try:
    len2_ort_max
except NameError:
    len2_ort_max = _sage_const_400 

try:
    len2_max
except NameError:
    len2_max = _sage_const_400 

#bound for no. of zeros in row or column of...
try:
    z_ort_max
except NameError:
    z_ort_max = _sage_const_1 

try:
    z_max
except NameError:
    z_max = _sage_const_1 

#maximal number of matrices
try:
    mat_num
except NameError:
    mat_num = _sage_const_1000 


#number of tries
try:
    lim_tries
except NameError:
    lim_tries = _sage_const_1000 


#Data file name
try:
    sym_mat_file_name
except NameError:
    sym_mat_file_name = '../Data/sym_mat '+str(ndim)+'x'+str(ndim)+' '+'rg '+str(rg)+'.dat'

#--------------------------------------------------------------------------------
#generation of orthogonal vector sets

t_mat_lst = []
ort_mat_lst = []
sym_mat_lst = []

try:
    t_mat_lst = load('../Data/t_mat_lst')
except Exception:
    t_mat_lst = []

try:
    ort_mat_lst = load('../Data/ort_mat_lst')
except Exception:
    ort_mat_lst = []

try:
    sym_mat_lst = load('../Data/sym_mat_lst')
except Exception:
    sym_mat_lst = []

try:
    sym_mat_unique = load('../Data/sym_mat_unique')
except Exception:
    sym_mat_unique = {}


E = identity_matrix(QQ, ndim)

for num_tries in range(lim_tries):

    t_mat = random_matrix(ZZ, rg, ndim, rank=rg, upper_bound = h_t_max)
    ort_mat, rel_mat = nice_GramSchmidtZ(t_mat)

    if not accept_matrix(ort_mat, allow_colinear=True,  max_zeros=z_ort_max, max_height = h_ort_max, max_len2 = len2_ort_max):
        continue
            
    lens2 = [rw * rw for rw in ort_mat.rows()]
    lens2.sort()

    #mid = (lens2[0]+lens2[-1])//2
    mid = lens2[len(lens2)//_sage_const_2 ]
    
    tau = _sage_const_1 
    #tau = mid
    if _sage_const_2 *rg > ndim:
       if lens2[-_sage_const_1 ] + lens2[_sage_const_0 ] > _sage_const_2 *mid:
          mid +=_sage_const_2 
       mid -= _sage_const_1 
       tau = mid

    sym_mat = ort_mat.transpose()*ort_mat - tau*E 

    if not accept_matrix(sym_mat, max_zeros=z_max, max_height = h_max, max_len2 = len2_max):
        continue

    if sym_mat in sym_mat_lst:
        continue

    evs = sym_mat.eigenmatrix_left()[_sage_const_0 ].diagonal()
    evs.sort()
    sig = tuple(evs)
    

    if t_mat not in t_mat_lst:
        t_mat_lst.append(t_mat)
        
    if ort_mat not in ort_mat_lst:
        ort_mat_lst.append(ort_mat)

    if sym_mat not in sym_mat_lst:
        sym_mat_lst.append(sym_mat)

    if sig in sym_mat_unique.keys():
        if sym_mat not in sym_mat_unique[sig]:
            sym_mat_unique[sig].append(sym_mat)
    else:
        sym_mat_unique[sig]=[sym_mat]

    if len(sym_mat_lst) >= mat_num:
        break

for j in range(len(sym_mat_lst)):
    print('+++++++++++++++')
    print('T=')
    print(t_mat_lst[j])
    print('Q=')
    print(ort_mat_lst[j])
    print('S=')
    print(sym_mat_lst[j])

for tp in sym_mat_unique.keys():
    print('===================')
    print(tp)
    print('+++++++++++++++++++')
    for mat in sym_mat_unique[tp]:
        print(mat)
        print('-------------------')


for tp in sym_mat_unique.keys():
    for mat in sym_mat_unique[tp]:
        while sym_mat_unique[tp].count(mat) > _sage_const_1 :
            sym_mat_unique[tp].remove(mat)
            

save(t_mat_lst, '../Data/t_mat_lst')
save(ort_mat_lst, '../Data/ort_mat_lst')
save(sym_mat_lst, '../Data/sym_mat_lst')
save(sym_mat_unique, '../Data/sym_mat_unique')

