

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_400 = Integer(400); _sage_const_100 = Integer(100); _sage_const_50 = Integer(50); _sage_const_1 = Integer(1); _sage_const_1000 = Integer(1000)
reset()

#the following parameters must be set-up before launching this script:

#number of rows and columns
ndim = _sage_const_3 

#rank bounds
rg = _sage_const_3 

#largest matrix elements
h_ort_max = _sage_const_400 
h_t_max = _sage_const_100 
h_max = _sage_const_50 

#bound for no. of zeros in row or column
z_ort_max = _sage_const_1 
z_max = _sage_const_1 

#maximal number of matrices
_mat_num = _sage_const_1000 

#number of tries
lim_tries = _sage_const_1000 

#starting id number
start_id = _sage_const_1 


#number of matrices
mat_num = _sage_const_100 

load('gensym.sage')
load('gendiag.sage')
load('genfiles.sage')

reset()

