

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20 = Integer(20); _sage_const_4 = Integer(4); _sage_const_17 = Integer(17); _sage_const_199 = Integer(199); _sage_const_1000 = Integer(1000); _sage_const_4000 = Integer(4000); _sage_const_16000 = Integer(16000)
reset()
#---------------------------------------------------------------------
#the following parameters must be set-up before launching this script:
res_max = _sage_const_20 
exp_len = _sage_const_4 

lo_prime = _sage_const_17 
hi_prime = _sage_const_199 

lo_a = _sage_const_1000 
hi_a = _sage_const_4000 
hi_b = _sage_const_16000 

pair_num = _sage_const_20 

load('genGCDpairs.sage')
load('genfiles.sage')
#---------------------------------------------------------------------
reset()

