

# This file was *autogenerated* from the file eigen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2)
eig1, eig2 = sample(range(-_sage_const_3 , _sage_const_4 ), _sage_const_2 )

