

# This file was *autogenerated* from the file genfiles.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
file_ext = '.xml'
tmpl_file_name = 'template' + file_ext

tmpl = open(tmpl_file_name, 'r')
otxt = tmpl.read()
tmpl.close()

#---------------------------------------------------------------------
#the following parameters must be set-up before launching this script:
try:
    start
except NameError:
    start=_sage_const_0 

try:
    poly_lst
except NameError:
    poly_lst = []
#---------------------------------------------------------------------
    
idx = start
for poly in poly_lst:

    polystr = str(poly[_sage_const_0 ]).replace('*', '')
    factorstr = str(factor(poly[_sage_const_0 ])).replace('*', '')
    ntxt = otxt    
    subs = {'$id$': str(idx), '$polystr$':str(poly[_sage_const_0 ]), '$factors$': polystr+' = '+factorstr,'$answ$':str(poly[_sage_const_1 ])}
    for s in subs.keys():
        ntxt = ntxt.replace(s, subs[s])
    file_name_pfx = 'Racionali šaknis variantas 1'
    outp = open(file_name_pfx + ' (' + str(idx) + ') ' + file_ext, 'w')
    outp.write(ntxt)
    outp.close()
    idx +=_sage_const_1 

