

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_13 = Integer(13); _sage_const_30 = Integer(30); _sage_const_20 = Integer(20); _sage_const_0 = Integer(0)
reset()
#---------------------------------------------------------------------
#the following parameters must be set-up before launching this script:
hi_prime = _sage_const_13 
hi_cfs = _sage_const_30 
poly_num = _sage_const_20 
start = _sage_const_0 

load('genRatRoot.sage')
load('genfiles.sage')
#---------------------------------------------------------------------
reset()

