

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_50 = Integer(50); _sage_const_20 = Integer(20); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0)
reset()
#---------------------------------------------------------------------
#the following parameters must be set-up before launching this script:


h_max = _sage_const_8 
v_max = _sage_const_50 
hi_cfs = _sage_const_20 

f_deg = _sage_const_4 
g_deg = _sage_const_2 

poly_num = _sage_const_20 
try_max = _sage_const_1000 

start = _sage_const_0 

#---------------------------------------------------------------------

load('genlongdiv.sage')
load('genfiles.sage')
#---------------------------------------------------------------------
reset()

