

# This file was *autogenerated* from the file genfiles.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
file_name_pfx = str(num_rows)+'x'+str(num_cols) + ' '
file_name_inf = 'Gramo - Šmito ortogonalizacija'
file_name_ext = '.xml'

tmpl_file_name = 'template.xml'

tmpl = open(tmpl_file_name, 'r')
otxt = tmpl.read()
tmpl.close()

#start of the numbering
start =_sage_const_1 

idx = start
for mat in mat_lst:
    ntxt = otxt
    rws = mat.rows()
    subs1 = {'$u'+str(j)+'$': latex(rws[j]) for j in range(len(rws))}
    subs2 = {'$eq'+str(j)+'$': eqs[j] for j in range(len(eqs))}
    subs3 = {'$id$': str(idx)}
    subs = {**subs1, **subs2, **subs3}
     
    for s in subs.keys():
        ntxt = ntxt.replace(s, subs[s])
    outp = open(file_name_pfx + 'rg ' + str(mat.rank()) + ' ' + file_name_inf + ' ' + str(idx) + ' variantas ' + file_name_ext, 'w')
    outp.write(ntxt)
    outp.close()
    idx +=_sage_const_1 

