

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000); _sage_const_5 = Integer(5)
reset()

#the following parameters must be set-up before launching this script:

#number of rows and columns
num_rows = _sage_const_3 
num_cols = _sage_const_3 


#rank bounds
rg_min = _sage_const_3 
rg_max = _sage_const_3 

#largest matrix elements
h_ort_max = _sage_const_20 
h_t_max = _sage_const_10 
h_max = _sage_const_20 

#bound for no. of zeros in row or column
z_ort_max = _sage_const_0 
z_t_max = _sage_const_0 
z_max = _sage_const_0 

#maximal number of matrices
ort_mat_num = _sage_const_20 
t_mat_num = _sage_const_20 

#number of tries
lim_tries = _sage_const_1000 

#starting id number
start = _sage_const_5 


#number of matrices
mat_num = _sage_const_10 

load('gengs1.sage')
load('gengs2.sage')
load('genfiles.sage')

reset()

