

# This file was *autogenerated* from the file genfiles.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
file_ext = '.xml'
tmpl_file_name = 'template' + file_ext

tmpl = open(tmpl_file_name, 'r')
otxt = tmpl.read()
tmpl.close()

#---------------------------------------------------------------------
#the following parameters must be set-up before launching this script:
try:
    start
except NameError:
    start=_sage_const_0 

try:
    mat_lst
except NameError:
    mat_lst = []
#---------------------------------------------------------------------
    
idx = start
for mat in mat_lst:
    ntxt = otxt    
    subs = {'$id$': str(idx), '$matrix$': latex(mat), '$echform$': latex(mat.echelon_form()), '$answ$': str(mat.rank())}
    for s in subs.keys():
        ntxt = ntxt.replace(s, subs[s])
    file_name_pfx = str(mat.nrows()) + 'x' + str(mat.ncolumns())+ ' r'+ str(mat.rank())
    outp = open(file_name_pfx + ' (' + str(idx) + ') ' + file_ext, 'w')
    outp.write(ntxt)
    outp.close()
    idx +=_sage_const_1 

