

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15)
reset()

#set-up script parameters
#largest matrix element (default value)
h_max = _sage_const_8 
#bound for no. of zeros in row or column
z_max = _sage_const_2 

#number of rows and columns
num_rows = _sage_const_4 
num_cols = _sage_const_4 

#rank bounds
rg_min = _sage_const_3 
rg_max = _sage_const_3 

#starting id number
start = _sage_const_0 


#number of matrices
mat_num = _sage_const_5 

load('genmat.sage')
load('genfiles.sage')

#---------------------------------------
reset()

#set-up script parameters
#largest matrix element (default value)
h_max = _sage_const_8 
#bound for no. of zeros in row or column
z_max = _sage_const_2 

#number of rows and columns
num_rows = _sage_const_4 
num_cols = _sage_const_4 

#---------------------------------------
#rank bounds
rg_min = _sage_const_4 
rg_max = _sage_const_4 

#starting id number
start = _sage_const_5 

#number of matrices
mat_num = _sage_const_5 

load('genmat.sage')
load('genfiles.sage')

#---------------------------------------
reset()

#set-up script parameters
#largest matrix element (default value)
h_max = _sage_const_8 
#bound for no. of zeros in row or column
z_max = _sage_const_2 

#number of rows and columns
num_rows = _sage_const_5 
num_cols = _sage_const_4 

#---------------------------------------
#rank bounds
rg_min = _sage_const_2 
rg_max = _sage_const_2 

#starting id number
start = _sage_const_10 


#number of matrices
mat_num = _sage_const_5 

load('genmat.sage')
load('genfiles.sage')

#---------------------------------------
reset()

#set-up script parameters
#largest matrix element (default value)
h_max = _sage_const_8 
#bound for no. of zeros in row or column
z_max = _sage_const_2 

#number of rows and columns
num_rows = _sage_const_4 
num_cols = _sage_const_5 

#---------------------------------------
#rank bounds
rg_min = _sage_const_2 
rg_max = _sage_const_2 

#starting id number
start = _sage_const_15 


#number of matrices
mat_num = _sage_const_5 

load('genmat.sage')
load('genfiles.sage')

reset()

