

# This file was *autogenerated* from the file stage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20)
reset()

#the following parameters must be set-up before launching this script:
#largest matrix element
h_max = _sage_const_8 
#starting file number
start = _sage_const_0 

#number of matrices
poly_num = _sage_const_20 

load('genpoly.sage')
load('genfiles.sage')

reset()

